spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/colleage_poi?serverTimezone=Asia/Shanghai&allowMultiQueries=true
    username: root
    password: ab654321
    driver-class-name: com.mysql.cj.jdbc.Driver


# 之前多了这个配置，导致启动的问题
#application:
#  name: Server